import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { AlertTriangle, Mail, Phone, FileText } from "lucide-react";

interface EscalationInfo {
  reason: string;
  recommended_target: string;
  info_to_pass_on: string;
}

interface EscalationPanelProps {
  escalation: EscalationInfo;
  gameName?: string;
  symptom?: string;
  onContinueAnyway: () => void;
  onEndSession: () => void;
}

export function EscalationPanel({ 
  escalation, 
  gameName, 
  symptom,
  onContinueAnyway, 
  onEndSession 
}: EscalationPanelProps) {
  const getTargetDetails = (target: string) => {
    switch (target.toLowerCase()) {
      case 'manufacturer':
        return {
          icon: <Phone className="h-5 w-5" />,
          label: 'Game Manufacturer',
          description: 'Contact the original equipment manufacturer for specialized support',
          color: 'bg-blue-500/10 text-blue-500 border-blue-500/20'
        };
      case 'distributor':
        return {
          icon: <Mail className="h-5 w-5" />,
          label: 'Equipment Distributor',
          description: 'Reach out to your equipment supplier for parts and technical guidance',
          color: 'bg-purple-500/10 text-purple-500 border-purple-500/20'
        };
      case 'specialist':
        return {
          icon: <AlertTriangle className="h-5 w-5" />,
          label: 'Certified Specialist',
          description: 'This requires a certified technician with specialized training',
          color: 'bg-orange-500/10 text-orange-500 border-orange-500/20'
        };
      default:
        return {
          icon: <FileText className="h-5 w-5" />,
          label: 'Expert Support',
          description: 'This issue requires expert-level troubleshooting',
          color: 'bg-red-500/10 text-red-500 border-red-500/20'
        };
    }
  };

  const targetDetails = getTargetDetails(escalation.recommended_target);

  const handleExportDetails = () => {
    const emailBody = `Game: ${gameName || 'Unknown'}
Symptom: ${symptom || 'Not specified'}

Escalation Reason:
${escalation.reason}

Technical Information:
${escalation.info_to_pass_on}

---
Generated by 1LevelUp Troubleshooting Assistant`;

    const mailto = `mailto:?subject=Escalation: ${gameName} - ${symptom?.substring(0, 50)}&body=${encodeURIComponent(emailBody)}`;
    window.location.href = mailto;
  };

  return (
    <Card className="border-2 border-orange-500/50 bg-orange-500/5">
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-2">
            <AlertTriangle className="h-6 w-6 text-orange-500" />
            <div>
              <CardTitle className="text-orange-500">Escalation Required</CardTitle>
              <CardDescription>This issue needs specialized attention</CardDescription>
            </div>
          </div>
          <Badge variant="outline" className={targetDetails.color}>
            {targetDetails.icon}
            <span className="ml-1">{targetDetails.label}</span>
          </Badge>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        <Alert>
          <AlertDescription className="text-sm">
            <strong>Why escalation is needed:</strong>
            <p className="mt-1">{escalation.reason}</p>
          </AlertDescription>
        </Alert>

        <div className="bg-muted/50 rounded-lg p-4">
          <h4 className="font-medium text-sm mb-2">Information to Share:</h4>
          <p className="text-sm text-muted-foreground whitespace-pre-wrap">
            {escalation.info_to_pass_on}
          </p>
        </div>

        <div className="bg-accent/50 rounded-lg p-4">
          <p className="text-sm text-muted-foreground">
            {targetDetails.description}
          </p>
        </div>

        <div className="flex gap-2">
          <Button 
            onClick={handleExportDetails}
            variant="default"
            className="flex-1"
          >
            <Mail className="h-4 w-4 mr-2" />
            Email Details
          </Button>
          <Button 
            onClick={onContinueAnyway}
            variant="outline"
            className="flex-1"
          >
            Continue Anyway
          </Button>
          <Button 
            onClick={onEndSession}
            variant="outline"
          >
            End Session
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
